require("dotenv").config();

const sqlite3 = require("sqlite3").verbose();
const { Client } = require("pg");
const path = require("path");

// ============================================================
// DATABASE CONNECTIONS
// ============================================================

const sqlitePath = path.join(__dirname, "quiz.db");

const sqlite = new sqlite3.Database(sqlitePath);

const pg = new Client({
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false
  }
});

// ============================================================
// SQLITE HELPERS
// ============================================================

function sqliteAll(sql, params = []) {
  return new Promise((resolve, reject) => {
    sqlite.all(sql, params, (error, rows) => {
      if (error) {
        reject(error);
      } else {
        resolve(rows);
      }
    });
  });
}

// ============================================================
// MAIN MIGRATION
// ============================================================

async function migrate() {
  try {
    console.log("");
    console.log("======================================");
    console.log("SQLite → PostgreSQL Migration");
    console.log("======================================");
    console.log("");

    // --------------------------------------------------------
    // Connect PostgreSQL
    // --------------------------------------------------------

    await pg.connect();

    console.log("PostgreSQL connected successfully.");

    // --------------------------------------------------------
    // Create tables
    // --------------------------------------------------------

    console.log("Creating PostgreSQL tables...");

    await pg.query(`
      CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT UNIQUE NOT NULL,
        password TEXT NOT NULL,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
      )
    `);

    await pg.query(`
      CREATE TABLE IF NOT EXISTS admins (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT UNIQUE NOT NULL,
        password TEXT NOT NULL,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
      )
    `);

    await pg.query(`
      CREATE TABLE IF NOT EXISTS exams (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        topic TEXT,
        start_time TEXT NOT NULL,
        end_time TEXT NOT NULL,
        duration_minutes INTEGER NOT NULL,
        rules TEXT,
        status TEXT DEFAULT 'SCHEDULED',
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
      )
    `);

    await pg.query(`
      CREATE TABLE IF NOT EXISTS questions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        exam_id INTEGER NOT NULL,
        question_text TEXT NOT NULL,
        option_a TEXT NOT NULL,
        option_b TEXT NOT NULL,
        option_c TEXT NOT NULL,
        option_d TEXT NOT NULL,
        correct_answer TEXT NOT NULL,
        explanation TEXT,
        question_order INTEGER,
        FOREIGN KEY (exam_id) REFERENCES exams(id)
      )
    `);

    await pg.query(`
      CREATE TABLE IF NOT EXISTS attempts (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        exam_id INTEGER NOT NULL,
        started_at TEXT,
        submitted_at TEXT,
        score REAL DEFAULT 0,
        total_questions INTEGER DEFAULT 0,
        correct_answers INTEGER DEFAULT 0,
        wrong_answers INTEGER DEFAULT 0,
        skipped_answers INTEGER DEFAULT 0,
        time_taken_seconds INTEGER DEFAULT 0,
        UNIQUE(user_id, exam_id),
        FOREIGN KEY (user_id) REFERENCES users(id),
        FOREIGN KEY (exam_id) REFERENCES exams(id)
      )
    `);

    await pg.query(`
      CREATE TABLE IF NOT EXISTS answers (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        attempt_id INTEGER NOT NULL,
        question_id INTEGER NOT NULL,
        selected_answer TEXT,
        is_correct INTEGER DEFAULT 0,
        FOREIGN KEY (attempt_id) REFERENCES attempts(id),
        FOREIGN KEY (question_id) REFERENCES questions(id)
      )
    `);

    console.log("Tables created.");
    console.log("");

    // --------------------------------------------------------
    // Read SQLite data
    // --------------------------------------------------------

    const users = await sqliteAll(`SELECT * FROM users`);
    const admins = await sqliteAll(`SELECT * FROM admins`);
    const exams = await sqliteAll(`SELECT * FROM exams`);
    const questions = await sqliteAll(`SELECT * FROM questions`);
    const attempts = await sqliteAll(`SELECT * FROM attempts`);
    const answers = await sqliteAll(`SELECT * FROM answers`);

    console.log(`Users:     ${users.length}`);
    console.log(`Admins:    ${admins.length}`);
    console.log(`Exams:     ${exams.length}`);
    console.log(`Questions: ${questions.length}`);
    console.log(`Attempts:  ${attempts.length}`);
    console.log(`Answers:   ${answers.length}`);
    console.log("");

    // --------------------------------------------------------
    // Transaction
    // --------------------------------------------------------

    await pg.query("BEGIN");

    // --------------------------------------------------------
    // USERS
    // --------------------------------------------------------

    for (const user of users) {
      await pg.query(
        `
        INSERT INTO users
          (id, name, email, password, created_at)
        VALUES
          ($1, $2, $3, $4, $5)
        ON CONFLICT (id) DO NOTHING
        `,
        [
          user.id,
          user.name,
          user.email,
          user.password,
          user.created_at
        ]
      );
    }

    console.log("Users migrated.");

    // --------------------------------------------------------
    // ADMINS
    // --------------------------------------------------------

    for (const admin of admins) {
      await pg.query(
        `
        INSERT INTO admins
          (id, name, email, password, created_at)
        VALUES
          ($1, $2, $3, $4, $5)
        ON CONFLICT (id) DO NOTHING
        `,
        [
          admin.id,
          admin.name,
          admin.email,
          admin.password,
          admin.created_at
        ]
      );
    }

    console.log("Admins migrated.");

    // --------------------------------------------------------
    // EXAMS
    // --------------------------------------------------------

    for (const exam of exams) {
      await pg.query(
        `
        INSERT INTO exams
          (id, title, topic, start_time, end_time,
           duration_minutes, rules, status, created_at)
        VALUES
          ($1, $2, $3, $4, $5, $6, $7, $8, $9)
        ON CONFLICT (id) DO NOTHING
        `,
        [
          exam.id,
          exam.title,
          exam.topic,
          exam.start_time,
          exam.end_time,
          exam.duration_minutes,
          exam.rules,
          exam.status,
          exam.created_at
        ]
      );
    }

    console.log("Exams migrated.");

    // --------------------------------------------------------
    // QUESTIONS
    // --------------------------------------------------------

    for (const question of questions) {
      await pg.query(
        `
        INSERT INTO questions
          (id, exam_id, question_text,
           option_a, option_b, option_c, option_d,
           correct_answer, explanation, question_order)
        VALUES
          ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
        ON CONFLICT (id) DO NOTHING
        `,
        [
          question.id,
          question.exam_id,
          question.question_text,
          question.option_a,
          question.option_b,
          question.option_c,
          question.option_d,
          question.correct_answer,
          question.explanation,
          question.question_order
        ]
      );
    }

    console.log("Questions migrated.");

    // --------------------------------------------------------
    // ATTEMPTS
    // --------------------------------------------------------

    for (const attempt of attempts) {
      await pg.query(
        `
        INSERT INTO attempts
          (id, user_id, exam_id,
           started_at, submitted_at,
           score, total_questions,
           correct_answers, wrong_answers,
           skipped_answers, time_taken_seconds)
        VALUES
          ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
        ON CONFLICT (id) DO NOTHING
        `,
        [
          attempt.id,
          attempt.user_id,
          attempt.exam_id,
          attempt.started_at,
          attempt.submitted_at,
          attempt.score,
          attempt.total_questions,
          attempt.correct_answers,
          attempt.wrong_answers,
          attempt.skipped_answers,
          attempt.time_taken_seconds
        ]
      );
    }

    console.log("Attempts migrated.");

    // --------------------------------------------------------
    // ANSWERS
    // --------------------------------------------------------

    for (const answer of answers) {
      await pg.query(
        `
        INSERT INTO answers
          (id, attempt_id, question_id,
           selected_answer, is_correct)
        VALUES
          ($1, $2, $3, $4, $5)
        ON CONFLICT (id) DO NOTHING
        `,
        [
          answer.id,
          answer.attempt_id,
          answer.question_id,
          answer.selected_answer,
          answer.is_correct
        ]
      );
    }

    console.log("Answers migrated.");

    // --------------------------------------------------------
    // RESET SEQUENCES
    // --------------------------------------------------------

    const tables = [
      "users",
      "admins",
      "exams",
      "questions",
      "attempts",
      "answers"
    ];

    for (const table of tables) {
      await pg.query(`
        SELECT setval(
          pg_get_serial_sequence('${table}', 'id'),
          COALESCE((SELECT MAX(id) FROM ${table}), 1),
          true
        )
      `);
    }

    console.log("Sequences updated.");

    // --------------------------------------------------------
    // COMMIT
    // --------------------------------------------------------

    await pg.query("COMMIT");

    console.log("");
    console.log("======================================");
    console.log("MIGRATION SUCCESSFUL");
    console.log("======================================");
    console.log("");

  } catch (error) {

    console.error("");
    console.error("MIGRATION FAILED:");
    console.error(error.message);

    try {
      await pg.query("ROLLBACK");
    } catch (rollbackError) {
      console.error("Rollback failed:", rollbackError.message);
    }

  } finally {

    sqlite.close();

    try {
      await pg.end();
    } catch (error) {
      // Ignore close error
    }
  }
}

migrate();